### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by A-AFTAHI** [felmoltor/DNSSnoopDogg#1]
Hey, thanks for the tool.
But till now i can't use it because of the following error:

Traceback (most recent call last):
	2: from ./dnssnoopdogg.rb:16:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- colorize (LoadError)

**Comment by marveon** [comment]
Having the same error, seems this project isn't maintained anymore!?

**Comment by Xitro01** [comment]
As can be read in the readme it requires the following gems:
colorize (0.6.0)
net-dns (0.8.0)

The following commands solve this issue:
sudo gem install colorize
sudo gem install net-dns
